version: '2'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./config/fpm-pool.conf:/etc/php7/php-fpm.d/zzz_custom.conf
    - ./config/php.ini:/etc/php7/conf.d/zzz_custom.ini
    - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    - ./src:/var/www/html
    restart: always
    ports:
    - 80:80
